export const INVENTORY_TYPES = ["PLASTIC", "MAILER", "ENVELOPE"];

export const CAT = {
  PLASTIC: {
    DEBIT: {
      MASTERCARD: {
        "MASTER CLASSIC": ["MC BPP NFC PRI","MC BPP NFC SUPPLY","MC PREM NFC PRI 2","MC PREMIUM NFC SUPP 2","RDA MC PREM NFC PRI","RDA MC PREM NFC SUPPLY","MC MUKAMMAL NFC PRI 2","MC MUKAMMAL NFC SUPPLY 2"],
        "MASTER SIGNATURE": ["MC SIG NFC PRI","MC SIG NFC SUPPLY"],
        "MASTER CLASSIC AMEEN": ["MC AMEEN PREM NFC PRI","MC AMEEN PREM NFC SUPPLY","RDA MC AMEEN PREM NFC PRI","RDA MC AMEEN PREM NFC SUPPLY"],
      },
      VISA: {
        "VISA CLASSIC": ["VC MEGA NFC PRIMARY 2","VC MEGA NFC SUPPLY 2","VISA READY LINE"],
        "VISA CLASSIC AMEEN": ["VC AMEEN NFC PRI","VC AMEEN NFC SUPPLY"],
        "VISA WOMEN (CONVENTIONAL)": ["VC WOMEN NFC PRI","VC WOMEN NFC SUPPLY"],
        "VISA AMEEN WOMEN (ISLAMIC)": ["VC AMEEN WOMEN NFC PRI","VC AMEEN WOMEN NFC SUPP"],
        "VISA INFINITE (CONVENTIONAL)": ["VC INFINITE NFC PRI","VC INFINITE NFC SUPPLY"],
        "VISA AMEEN INFINITE (ISLAMIC)": ["VISA AMEEN INFINITE (ISLAMIC)"],
        "VISA PREMIUM PLUS (CONVENTIONAL)": ["VC PREMIUM PLUS NFC PRI","VC PREMIUM PLUS NFC SUPPLY"],
        "VISA AMEEN PREMIUM PLUS (ISLAMIC)": ["VC AMEEN PREMIUM PLUS NFC PRI","VC AMEEN PREMIUM PLUS NFC SUPPLY"],
        "VISA FREELANCER (CONVENTIONAL)": ["VISA FREE LANCER NFC PRI","VISA FREE LANCER NFC SUPPLY","VC FCY AED NFC PRI","VC FCY EUR NFC PRI","VC FCY GBP NFC PRI","VC FCY SAR NFC PRI","VC FCY USD NFC PRI"],
        "VISA AMEEN FREELANCER (ISLAMIC)": ["VISA FREE LANCER NFC AMEEN","VISA FREE LANCER NFC AMEEN SUPPLY","VC AMEEN FCY AED NFC","VC AMEEN FCY EUR NFC","VC AMEEN FCY GBP NFC","VC AMEEN FCY SAR NFC","VC AMEEN FCY USD NFC"],
        "VISA UAE CLASSIC": ["UAE VISA CLASSIC NFC"],
        "VISA UAE PAYROLL": ["UAE PAY ROLL (WIZ) NFC"],
        "VISA UAE SIGNATURE PLATINUM": ["UAE SIGNATURE (PLATINUM) NFC"],
      },
      PAYPAK: {
        "PAYPAK AMEEN": ["PAYPAK AMEEN NFC PRI","PAYPAK AMEEN NFC SUPPLY"],
        "PAYPAK CONVENTIONAL": ["PAYPAK NFC PRI","PAYPAK NFC SUPPLY"],
        "PAYPAK OMNI NFC": ["PAYPAK OMNI NONPREPAID NFC"],
      },
      "UNION PAY": { "UPI CLASSIC": ["UPI NFC PRI","UPI NFC SUPPLY"] },
    },
    CREDIT: {
      VISA: {
        "VISA SILVER": ["CREDIT CARD VISA CLASSIC"],
        "VISA GOLD": ["CREDIT CARD VISA GOLD"],
        "VISA PLATINUM": ["CREDIT CARD VISA PLATINUM"],
      },
    },
  },
  MAILER: {
    DEBIT: {
      MASTERCARD: {
        "MASTER CLASSIC": ["MC BPP NFC PRI","MC BPP NFC SUPPLY","MC PREM NFC PRI 2","MC PREMIUM NFC SUPP 2","RDA MC PREM NFC PRI","RDA MC PREM NFC SUPPLY","MC MUKAMMAL NFC PRI 2","MC MUKAMMAL NFC SUPPLY 2"],
        "MASTER SIGNATURE": ["MC SIG NFC PRI","MC SIG NFC SUPPLY"],
        "MASTER CLASSIC AMEEN": ["MC AMEEN PREM NFC PRI","MC AMEEN PREM NFC SUPPLY","RDA MC AMEEN PREM NFC PRI","RDA MC AMEEN PREM NFC SUPPLY"],
      },
      VISA: {
        "VISA CLASSIC": ["VC MEGA NFC PRIMARY 2","VC MEGA NFC SUPPLY 2","VISA READY LINE"],
        "VISA CLASSIC AMEEN": ["VC AMEEN NFC PRI","VC AMEEN NFC SUPPLY"],
        "VISA WOMEN (CONVENTIONAL)": ["VC WOMEN NFC PRI","VC WOMEN NFC SUPPLY"],
        "VISA AMEEN WOMEN (ISLAMIC)": ["VC AMEEN WOMEN NFC PRI","VC AMEEN WOMEN NFC SUPP"],
        "VISA INFINITE (CONVENTIONAL)": ["VC INFINITE NFC PRI","VC INFINITE NFC SUPPLY"],
        "VISA AMEEN INFINITE (ISLAMIC)": ["VISA AMEEN INFINITE (ISLAMIC)"],
        "VISA PREMIUM PLUS (CONVENTIONAL)": ["VC PREMIUM PLUS NFC PRI","VC PREMIUM PLUS NFC SUPPLY"],
        "VISA AMEEN PREMIUM PLUS (ISLAMIC)": ["VC AMEEN PREMIUM PLUS NFC PRI","VC AMEEN PREMIUM PLUS NFC SUPPLY"],
        "VISA FREELANCER (CONVENTIONAL)": ["VISA FREE LANCER NFC PRI","VISA FREE LANCER NFC SUPPLY","VC FCY AED NFC PRI","VC FCY EUR NFC PRI","VC FCY GBP NFC PRI","VC FCY SAR NFC PRI","VC FCY USD NFC PRI"],
        "VISA AMEEN FREELANCER (ISLAMIC)": ["VISA FREE LANCER NFC AMEEN","VISA FREE LANCER NFC AMEEN SUPPLY","VC AMEEN FCY AED NFC","VC AMEEN FCY EUR NFC","VC AMEEN FCY GBP NFC","VC AMEEN FCY SAR NFC","VC AMEEN FCY USD NFC"],
        "VISA UAE CLASSIC": ["UAE VISA CLASSIC NFC"],
        "VISA UAE PAYROLL": ["UAE PAY ROLL (WIZ) NFC"],
        "VISA UAE SIGNATURE PLATINUM": ["UAE SIGNATURE (PLATINUM) NFC"],
      },
      PAYPAK: {
        "PAYPAK AMEEN": ["PAYPAK AMEEN NFC PRI","PAYPAK AMEEN NFC SUPPLY"],
        "PAYPAK CONVENTIONAL": ["PAYPAK NFC PRI","PAYPAK NFC SUPPLY"],
        "PAYPAK OMNI NFC": ["PAYPAK OMNI NONPREPAID NFC"],
      },
      "UNION PAY": { "UPI CLASSIC": ["UPI NFC PRI","UPI NFC SUPPLY"] },
    },
    CREDIT: {
      VISA: {
        "VISA SILVER": ["CREDIT CARD VISA CLASSIC"],
        "VISA GOLD": ["CREDIT CARD VISA GOLD"],
        "VISA PLATINUM": ["CREDIT CARD VISA PLATINUM"],
      },
    },
  },
  ENVELOPE: {
   DEBIT: {
      STANDARD: {
        "STANDARD ENVELOPE": ["STD ENVELOPE A4","STD ENVELOPE DL","STD ENVELOPE C5"],
        "PREMIUM ENVELOPE": ["PREM ENVELOPE A4","PREM ENVELOPE DL"],
        "AMEEN ENVELOPE": ["AMEEN ENVELOPE A4","AMEEN ENVELOPE DL"],
      },
    },
    CREDIT: {
      STANDARD: {
        "STANDARD CREDIT ENVELOPE": ["CREDIT ENVELOPE A4","CREDIT ENVELOPE DL"],
        "PREMIUM CREDIT ENVELOPE": ["PREM CREDIT ENVELOPE A4","PREM CREDIT ENVELOPE DL"],
      },
    },
  },
};

export const VENDORS = ["Rayyan Co","Secure Print","Info Tel","Ademia","Other"];
// add this at the bottom
export const SESSION_KEY = "ims_current_site";
export const SITE_USERS = {
  KHI: { username:"khi_admin", password:"khi@123", label:"Karachi HQ", abbr:"KHI" },
  LHE: { username:"lhe_admin", password:"lhe@123", label:"Lahore Branch", abbr:"LHE" },
};
